#!/bin/bash

gs_convert() {
	echo $1 $2 ${2/png/eps}
	gs -q -dEPSCrop -dSAFER -dNOPAUSE -dBATCH -sDEVICE=epswrite \
	-sOutputFile=${2/png/eps} $1
	gs -q -dEPSCrop -dSAFER -dNOPAUSE -dBATCH -sDEVICE=pnggray \
	-sOutputFile=$2 ${2/png/eps}
	rm ${2/png/eps}
}
gs_convert chess-pieces.1 wwp.png; gs_convert chess-pieces.2 bwp.png
gs_convert chess-pieces.3 wwr.png; gs_convert chess-pieces.4 bwr.png
gs_convert chess-pieces.5 wwn.png; gs_convert chess-pieces.6 bwn.png
gs_convert chess-pieces.7 wwb.png; gs_convert chess-pieces.8 bwb.png
gs_convert chess-pieces.9 wwq.png; gs_convert chess-pieces.10 bwq.png
gs_convert chess-pieces.11 wwk.png; gs_convert chess-pieces.12 bwk.png
gs_convert chess-pieces.13 wbp.png; gs_convert chess-pieces.14 bbp.png
gs_convert chess-pieces.15 wbr.png; gs_convert chess-pieces.16 bbr.png
gs_convert chess-pieces.17 wbn.png; gs_convert chess-pieces.18 bbn.png
gs_convert chess-pieces.19 wbb.png; gs_convert chess-pieces.20 bbb.png
gs_convert chess-pieces.21 wbq.png; gs_convert chess-pieces.22 bbq.png
gs_convert chess-pieces.23 wbk.png; gs_convert chess-pieces.24 bbk.png
gs_convert chess-pieces.25 ws.png
gs_convert chess-pieces.26 bs.png
