#!/bin/bash

convert chess-pieces.1 wwp.gif; convert chess-pieces.2 bwp.gif
convert chess-pieces.3 wwr.gif; convert chess-pieces.4 bwr.gif
convert chess-pieces.5 wwn.gif; convert chess-pieces.6 bwn.gif
convert chess-pieces.7 wwb.gif; convert chess-pieces.8 bwb.gif
convert chess-pieces.9 wwq.gif; convert chess-pieces.10 bwq.gif
convert chess-pieces.11 wwk.gif; convert chess-pieces.12 bwk.gif
convert chess-pieces.13 wbp.gif; convert chess-pieces.14 bbp.gif
convert chess-pieces.15 wbr.gif; convert chess-pieces.16 bbr.gif
convert chess-pieces.17 wbn.gif; convert chess-pieces.18 bbn.gif
convert chess-pieces.19 wbb.gif; convert chess-pieces.20 bbb.gif
convert chess-pieces.21 wbq.gif; convert chess-pieces.22 bbq.gif
convert chess-pieces.23 wbk.gif; convert chess-pieces.24 bbk.gif
convert chess-pieces.25 ws.gif
convert chess-pieces.26 bs.gif
